-- local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
-- if not vim.loop.fs_stat(lazypath) then
--   vim.fn.system({
--     "git",
--     "clone",
--     "--filter=blob:none",
--     "https://github.com/folke/lazy.nvim.git",
--     "--branch=stable", -- latest stable release
--     lazypath,
--   })
-- end
-- vim.opt.rtp:prepend(lazypath)
--
-- require("lazy").setup({
--   { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
--   { "nvim-treesitter/nvim-treesitter", name = "treesitter"},
--   { "theprimeagen/harpoon" },
--   {     
--     'nvim-telescope/telescope.nvim', tag = '0.1.5',
--       dependencies = { 'nvim-lua/plenary.nvim' }
--   },
--   {"jesseduffield/lazygit"},
--   {'VonHeikemen/lsp-zero.nvim', branch = 'v3.x'},
--   {'neovim/nvim-lspconfig'},
--   {'hrsh7th/cmp-nvim-lsp'},
--   {'hrsh7th/nvim-cmp'},
--   {'L3MON4D3/LuaSnip'},
-- })
-- vim.cmd.colorscheme "catppuccin"
--
-- local lsp_zero = require('lsp-zero')
--
-- lsp_zero.on_attach(function(client, bufnr)
--   -- see :help lsp-zero-keybindings
--   -- to learn the available actions
--   lsp_zero.default_keymaps({buffer = bufnr})
-- end)
--
-- lsp_zero.setup_servers({'tsserver', 'rust_analyzer', "gopls"})
-- require("ove.remap")
--
-- require("lazy".setup("plugins"))
